### ISSUE TITLE
Sytax Error

### ISSUE THREAD

**Issue by gebanntgekickt** [jflessau/winbot-twitter-bot#11]
Sry I get an syntax error in this part of the code:

print "\n\n\nstart cycle: " +str(i + 1)

Regards

**Comment by jflessau** [comment]
Are you using python 3? In python 3 *print* is a function. So you cloud change 
`print "some text"`
to
`print("some text")"`

Or wait a few minutes. I'll update this repository and fix this :hourglass:

**Comment by jflessau** [comment]
Done. 
Download this repo and try it again. 
If any other errors occour, please let me know :)

**Comment by gebanntgekickt** [comment]
Thx for the quick support, the Bot is running but after following one tweet this error occurs:
Traceback (most recent call last):
  File "C:\Users\Luca Thun\Desktop\Twitter Projekt\winbot-twitter-bot-master\winbot.py", line 289, in <module>
    win_things()
  File "C:\Users\Luca Thun\Desktop\Twitter Projekt\winbot-twitter-bot-master\winbot.py", line 35, in win_things
    get_intimate_with(filtered_tweets)
  File "C:\Users\Luca Thun\Desktop\Twitter Projekt\winbot-twitter-bot-master\winbot.py", line 116, in get_intimate_with
    follow_author(tweet)
  File "C:\Users\Luca Thun\Desktop\Twitter Projekt\winbot-twitter-bot-master\winbot.py", line 177, in follow_author
    followed_num = follow_user(tweet["user"]["screen_name"])
  File "C:\Users\Luca Thun\Desktop\Twitter Projekt\winbot-twitter-bot-master\winbot.py", line 169, in follow_user
    print("followed " + screen_name.encode("ascii", "ignore"))
TypeError: must be str, not bytes

Thank you so much for the support

**Comment by gebanntgekickt** [comment]
Thx for the uick support, the Bot runs but the following error occurs after following one tweet:
Traceback (most recent call last):
  File "C:\Users\XX\Desktop\winbot-twitter-bot-master\winbot.py", line 289, in <module>
    win_things()
  File "C:\Users\XX\Desktop\winbot-twitter-bot-master\winbot.py", line 35, in win_things
    get_intimate_with(filtered_tweets)
  File "C:\Users\XX\Desktop\winbot-twitter-bot-master\winbot.py", line 116, in get_intimate_with
    follow_author(tweet)
  File "C:\Users\XX\Desktop\winbot-twitter-bot-master\winbot.py", line 177, in follow_author
    followed_num = follow_user(tweet["user"]["screen_name"])
  File "C:\Users\XX\Desktop\winbot-twitter-bot-master\winbot.py", line 169, in follow_user
    print("followed " + screen_name.encode("ascii", "ignore"))
TypeError: must be str, not bytes

Thx for your support!

**Comment by jflessau** [comment]
This seems to be an error that can’t solved for python 2 an 3 at the same time. Unfortunately, the only option would be using python 2.

**Comment by gebanntgekickt** [comment]
I fixed it by converting it to string

does the blacklist work for your bot? It seems that despite some user are in the blacklist the bot still retweets tweets of these users

**Comment by jflessau** [comment]
So far, the blacklist seems to work. I’ll have an eye on that one. 

Would you mind posting the line that fixed the previous error?

**Comment by gebanntgekickt** [comment]
witter.create_friendship(screen_name=screen_name)
            add_line(screen_name, "follows.txt")
            print("followed " + str(screen_name.encode("ascii", "ignore")))
        except TwythonError as e:
            print("FAILED to follow " + str(screen_name.encode("ascii", "ignore")))
