### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by sa-ba01** [jflessau/winbot-twitter-bot#17]
Hello, I made 5 bots running on my raspberry Pi, 4 Bots are running without any problem, but the fifth bot has this error (I don't know how to fix it, it's the same code on all of the 5 bots):

`start cycle: 1
Traceback (most recent call last):
  File "winbot.py", line 289, in <module>
    win_things()
  File "winbot.py", line 31, in win_things
    filtered_tweets = filter_tweets(fresh_tweets)
  File "winbot.py", line 65, in filter_tweets
    tweets = past_retweets_filter(tweets)
  File "winbot.py", line 93, in past_retweets_filter
    past_retweets = get_past_retweets()
  File "winbot.py", line 50, in get_past_retweets
    line = line[3]
IndexError: list index out of range
`
What did I make wrong?

**Comment by jflessau** [comment]
Seems like something is wrong with your `log.txt`. Try to replace it with the default one.
